version: '3.7'

services:
  db:
    container_name: "proyect_database"
    platform: linux/x86_64
    build:
      context: ./Database
      dockerfile: db.Dockerfile
    networks: 
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "proyect"
      MYSQL_USER: "proyect_user"
      MYSQL_PASSWORD: "secret"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  backend:
    container_name: "proyect_backend"
    build:
      context: ./Backend
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./Backend:/api-backend/
  frontend:
    container_name: "proyect_frontend"
    build: 
      context: ./Frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
       - ./Frontend:/api-frontend/
networks:
  default:
volumes:
  mysql_data:
    
    
